baseURL = 'http://open-native.com/learning/scrapbook'
languageCode = 'zh-CN'
languageName = "简体中文"
title = '云原生·盐酒猿'
theme = 'tranquilpeak'


# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "article"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/article/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = "文章"
  [[menu.main]]
    weight = 2
    identifier = "scrapbook"
    pre = ""
    post = ""
    name = "学习札记"
    url = "/scrapbook/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
